// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto/article/article_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	article "github.com/loak155/techbranch-backend/proto/article"
	grpc "google.golang.org/grpc"
)

// MockArticleServiceClient is a mock of ArticleServiceClient interface.
type MockArticleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServiceClientMockRecorder
}

// MockArticleServiceClientMockRecorder is the mock recorder for MockArticleServiceClient.
type MockArticleServiceClientMockRecorder struct {
	mock *MockArticleServiceClient
}

// NewMockArticleServiceClient creates a new mock instance.
func NewMockArticleServiceClient(ctrl *gomock.Controller) *MockArticleServiceClient {
	mock := &MockArticleServiceClient{ctrl: ctrl}
	mock.recorder = &MockArticleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleServiceClient) EXPECT() *MockArticleServiceClientMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockArticleServiceClient) CreateArticle(ctx context.Context, in *article.CreateArticleRequest, opts ...grpc.CallOption) (*article.CreateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateArticle", varargs...)
	ret0, _ := ret[0].(*article.CreateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockArticleServiceClientMockRecorder) CreateArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).CreateArticle), varargs...)
}

// DecrementBookmarksCount mocks base method.
func (m *MockArticleServiceClient) DecrementBookmarksCount(ctx context.Context, in *article.DecrementBookmarksCountRequest, opts ...grpc.CallOption) (*article.DecrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DecrementBookmarksCount", varargs...)
	ret0, _ := ret[0].(*article.DecrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBookmarksCount indicates an expected call of DecrementBookmarksCount.
func (mr *MockArticleServiceClientMockRecorder) DecrementBookmarksCount(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBookmarksCount", reflect.TypeOf((*MockArticleServiceClient)(nil).DecrementBookmarksCount), varargs...)
}

// DecrementBookmarksCountCompensate mocks base method.
func (m *MockArticleServiceClient) DecrementBookmarksCountCompensate(ctx context.Context, in *article.DecrementBookmarksCountRequest, opts ...grpc.CallOption) (*article.DecrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DecrementBookmarksCountCompensate", varargs...)
	ret0, _ := ret[0].(*article.DecrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBookmarksCountCompensate indicates an expected call of DecrementBookmarksCountCompensate.
func (mr *MockArticleServiceClientMockRecorder) DecrementBookmarksCountCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBookmarksCountCompensate", reflect.TypeOf((*MockArticleServiceClient)(nil).DecrementBookmarksCountCompensate), varargs...)
}

// DeleteArticle mocks base method.
func (m *MockArticleServiceClient) DeleteArticle(ctx context.Context, in *article.DeleteArticleRequest, opts ...grpc.CallOption) (*article.DeleteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteArticle", varargs...)
	ret0, _ := ret[0].(*article.DeleteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockArticleServiceClientMockRecorder) DeleteArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).DeleteArticle), varargs...)
}

// GetArticle mocks base method.
func (m *MockArticleServiceClient) GetArticle(ctx context.Context, in *article.GetArticleRequest, opts ...grpc.CallOption) (*article.GetArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticle", varargs...)
	ret0, _ := ret[0].(*article.GetArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleServiceClientMockRecorder) GetArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).GetArticle), varargs...)
}

// IncrementBookmarksCount mocks base method.
func (m *MockArticleServiceClient) IncrementBookmarksCount(ctx context.Context, in *article.IncrementBookmarksCountRequest, opts ...grpc.CallOption) (*article.IncrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IncrementBookmarksCount", varargs...)
	ret0, _ := ret[0].(*article.IncrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementBookmarksCount indicates an expected call of IncrementBookmarksCount.
func (mr *MockArticleServiceClientMockRecorder) IncrementBookmarksCount(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBookmarksCount", reflect.TypeOf((*MockArticleServiceClient)(nil).IncrementBookmarksCount), varargs...)
}

// IncrementBookmarksCountCompensate mocks base method.
func (m *MockArticleServiceClient) IncrementBookmarksCountCompensate(ctx context.Context, in *article.IncrementBookmarksCountRequest, opts ...grpc.CallOption) (*article.IncrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IncrementBookmarksCountCompensate", varargs...)
	ret0, _ := ret[0].(*article.IncrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementBookmarksCountCompensate indicates an expected call of IncrementBookmarksCountCompensate.
func (mr *MockArticleServiceClientMockRecorder) IncrementBookmarksCountCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBookmarksCountCompensate", reflect.TypeOf((*MockArticleServiceClient)(nil).IncrementBookmarksCountCompensate), varargs...)
}

// ListArticles mocks base method.
func (m *MockArticleServiceClient) ListArticles(ctx context.Context, in *article.ListArticlesRequest, opts ...grpc.CallOption) (*article.ListArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListArticles", varargs...)
	ret0, _ := ret[0].(*article.ListArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockArticleServiceClientMockRecorder) ListArticles(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockArticleServiceClient)(nil).ListArticles), varargs...)
}

// UpdateArticle mocks base method.
func (m *MockArticleServiceClient) UpdateArticle(ctx context.Context, in *article.UpdateArticleRequest, opts ...grpc.CallOption) (*article.UpdateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateArticle", varargs...)
	ret0, _ := ret[0].(*article.UpdateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockArticleServiceClientMockRecorder) UpdateArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).UpdateArticle), varargs...)
}

// MockArticleServiceServer is a mock of ArticleServiceServer interface.
type MockArticleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServiceServerMockRecorder
}

// MockArticleServiceServerMockRecorder is the mock recorder for MockArticleServiceServer.
type MockArticleServiceServerMockRecorder struct {
	mock *MockArticleServiceServer
}

// NewMockArticleServiceServer creates a new mock instance.
func NewMockArticleServiceServer(ctrl *gomock.Controller) *MockArticleServiceServer {
	mock := &MockArticleServiceServer{ctrl: ctrl}
	mock.recorder = &MockArticleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleServiceServer) EXPECT() *MockArticleServiceServerMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockArticleServiceServer) CreateArticle(arg0 context.Context, arg1 *article.CreateArticleRequest) (*article.CreateArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(*article.CreateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockArticleServiceServerMockRecorder) CreateArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).CreateArticle), arg0, arg1)
}

// DecrementBookmarksCount mocks base method.
func (m *MockArticleServiceServer) DecrementBookmarksCount(arg0 context.Context, arg1 *article.DecrementBookmarksCountRequest) (*article.DecrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementBookmarksCount", arg0, arg1)
	ret0, _ := ret[0].(*article.DecrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBookmarksCount indicates an expected call of DecrementBookmarksCount.
func (mr *MockArticleServiceServerMockRecorder) DecrementBookmarksCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBookmarksCount", reflect.TypeOf((*MockArticleServiceServer)(nil).DecrementBookmarksCount), arg0, arg1)
}

// DecrementBookmarksCountCompensate mocks base method.
func (m *MockArticleServiceServer) DecrementBookmarksCountCompensate(arg0 context.Context, arg1 *article.DecrementBookmarksCountRequest) (*article.DecrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementBookmarksCountCompensate", arg0, arg1)
	ret0, _ := ret[0].(*article.DecrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBookmarksCountCompensate indicates an expected call of DecrementBookmarksCountCompensate.
func (mr *MockArticleServiceServerMockRecorder) DecrementBookmarksCountCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBookmarksCountCompensate", reflect.TypeOf((*MockArticleServiceServer)(nil).DecrementBookmarksCountCompensate), arg0, arg1)
}

// DeleteArticle mocks base method.
func (m *MockArticleServiceServer) DeleteArticle(arg0 context.Context, arg1 *article.DeleteArticleRequest) (*article.DeleteArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", arg0, arg1)
	ret0, _ := ret[0].(*article.DeleteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockArticleServiceServerMockRecorder) DeleteArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).DeleteArticle), arg0, arg1)
}

// GetArticle mocks base method.
func (m *MockArticleServiceServer) GetArticle(arg0 context.Context, arg1 *article.GetArticleRequest) (*article.GetArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", arg0, arg1)
	ret0, _ := ret[0].(*article.GetArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleServiceServerMockRecorder) GetArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).GetArticle), arg0, arg1)
}

// IncrementBookmarksCount mocks base method.
func (m *MockArticleServiceServer) IncrementBookmarksCount(arg0 context.Context, arg1 *article.IncrementBookmarksCountRequest) (*article.IncrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementBookmarksCount", arg0, arg1)
	ret0, _ := ret[0].(*article.IncrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementBookmarksCount indicates an expected call of IncrementBookmarksCount.
func (mr *MockArticleServiceServerMockRecorder) IncrementBookmarksCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBookmarksCount", reflect.TypeOf((*MockArticleServiceServer)(nil).IncrementBookmarksCount), arg0, arg1)
}

// IncrementBookmarksCountCompensate mocks base method.
func (m *MockArticleServiceServer) IncrementBookmarksCountCompensate(arg0 context.Context, arg1 *article.IncrementBookmarksCountRequest) (*article.IncrementBookmarksCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementBookmarksCountCompensate", arg0, arg1)
	ret0, _ := ret[0].(*article.IncrementBookmarksCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementBookmarksCountCompensate indicates an expected call of IncrementBookmarksCountCompensate.
func (mr *MockArticleServiceServerMockRecorder) IncrementBookmarksCountCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBookmarksCountCompensate", reflect.TypeOf((*MockArticleServiceServer)(nil).IncrementBookmarksCountCompensate), arg0, arg1)
}

// ListArticles mocks base method.
func (m *MockArticleServiceServer) ListArticles(arg0 context.Context, arg1 *article.ListArticlesRequest) (*article.ListArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", arg0, arg1)
	ret0, _ := ret[0].(*article.ListArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockArticleServiceServerMockRecorder) ListArticles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockArticleServiceServer)(nil).ListArticles), arg0, arg1)
}

// UpdateArticle mocks base method.
func (m *MockArticleServiceServer) UpdateArticle(arg0 context.Context, arg1 *article.UpdateArticleRequest) (*article.UpdateArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1)
	ret0, _ := ret[0].(*article.UpdateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockArticleServiceServerMockRecorder) UpdateArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).UpdateArticle), arg0, arg1)
}

// mustEmbedUnimplementedArticleServiceServer mocks base method.
func (m *MockArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArticleServiceServer")
}

// mustEmbedUnimplementedArticleServiceServer indicates an expected call of mustEmbedUnimplementedArticleServiceServer.
func (mr *MockArticleServiceServerMockRecorder) mustEmbedUnimplementedArticleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArticleServiceServer", reflect.TypeOf((*MockArticleServiceServer)(nil).mustEmbedUnimplementedArticleServiceServer))
}

// MockUnsafeArticleServiceServer is a mock of UnsafeArticleServiceServer interface.
type MockUnsafeArticleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeArticleServiceServerMockRecorder
}

// MockUnsafeArticleServiceServerMockRecorder is the mock recorder for MockUnsafeArticleServiceServer.
type MockUnsafeArticleServiceServerMockRecorder struct {
	mock *MockUnsafeArticleServiceServer
}

// NewMockUnsafeArticleServiceServer creates a new mock instance.
func NewMockUnsafeArticleServiceServer(ctrl *gomock.Controller) *MockUnsafeArticleServiceServer {
	mock := &MockUnsafeArticleServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeArticleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeArticleServiceServer) EXPECT() *MockUnsafeArticleServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedArticleServiceServer mocks base method.
func (m *MockUnsafeArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArticleServiceServer")
}

// mustEmbedUnimplementedArticleServiceServer indicates an expected call of mustEmbedUnimplementedArticleServiceServer.
func (mr *MockUnsafeArticleServiceServerMockRecorder) mustEmbedUnimplementedArticleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArticleServiceServer", reflect.TypeOf((*MockUnsafeArticleServiceServer)(nil).mustEmbedUnimplementedArticleServiceServer))
}
