// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto/comment/comment_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	comment "github.com/loak155/techbranch-backend/proto/comment"
	grpc "google.golang.org/grpc"
)

// MockCommentServiceClient is a mock of CommentServiceClient interface.
type MockCommentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceClientMockRecorder
}

// MockCommentServiceClientMockRecorder is the mock recorder for MockCommentServiceClient.
type MockCommentServiceClientMockRecorder struct {
	mock *MockCommentServiceClient
}

// NewMockCommentServiceClient creates a new mock instance.
func NewMockCommentServiceClient(ctrl *gomock.Controller) *MockCommentServiceClient {
	mock := &MockCommentServiceClient{ctrl: ctrl}
	mock.recorder = &MockCommentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentServiceClient) EXPECT() *MockCommentServiceClientMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentServiceClient) CreateComment(ctx context.Context, in *comment.CreateCommentRequest, opts ...grpc.CallOption) (*comment.CreateCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateComment", varargs...)
	ret0, _ := ret[0].(*comment.CreateCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceClientMockRecorder) CreateComment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentServiceClient)(nil).CreateComment), varargs...)
}

// DeleteComment mocks base method.
func (m *MockCommentServiceClient) DeleteComment(ctx context.Context, in *comment.DeleteCommentRequest, opts ...grpc.CallOption) (*comment.DeleteCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteComment", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceClientMockRecorder) DeleteComment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteComment), varargs...)
}

// DeleteCommentByArticleID mocks base method.
func (m *MockCommentServiceClient) DeleteCommentByArticleID(ctx context.Context, in *comment.DeleteCommentByArticleIDRequest, opts ...grpc.CallOption) (*comment.DeleteCommentByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCommentByArticleID", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByArticleID indicates an expected call of DeleteCommentByArticleID.
func (mr *MockCommentServiceClientMockRecorder) DeleteCommentByArticleID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByArticleID", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteCommentByArticleID), varargs...)
}

// DeleteCommentByArticleIDCompensate mocks base method.
func (m *MockCommentServiceClient) DeleteCommentByArticleIDCompensate(ctx context.Context, in *comment.DeleteCommentByArticleIDRequest, opts ...grpc.CallOption) (*comment.DeleteCommentByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCommentByArticleIDCompensate", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByArticleIDCompensate indicates an expected call of DeleteCommentByArticleIDCompensate.
func (mr *MockCommentServiceClientMockRecorder) DeleteCommentByArticleIDCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByArticleIDCompensate", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteCommentByArticleIDCompensate), varargs...)
}

// DeleteCommentByUserID mocks base method.
func (m *MockCommentServiceClient) DeleteCommentByUserID(ctx context.Context, in *comment.DeleteCommentByUserIDRequest, opts ...grpc.CallOption) (*comment.DeleteCommentByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCommentByUserID", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByUserID indicates an expected call of DeleteCommentByUserID.
func (mr *MockCommentServiceClientMockRecorder) DeleteCommentByUserID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByUserID", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteCommentByUserID), varargs...)
}

// DeleteCommentByUserIDCompensate mocks base method.
func (m *MockCommentServiceClient) DeleteCommentByUserIDCompensate(ctx context.Context, in *comment.DeleteCommentByUserIDRequest, opts ...grpc.CallOption) (*comment.DeleteCommentByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCommentByUserIDCompensate", varargs...)
	ret0, _ := ret[0].(*comment.DeleteCommentByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByUserIDCompensate indicates an expected call of DeleteCommentByUserIDCompensate.
func (mr *MockCommentServiceClientMockRecorder) DeleteCommentByUserIDCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByUserIDCompensate", reflect.TypeOf((*MockCommentServiceClient)(nil).DeleteCommentByUserIDCompensate), varargs...)
}

// GetComment mocks base method.
func (m *MockCommentServiceClient) GetComment(ctx context.Context, in *comment.GetCommentRequest, opts ...grpc.CallOption) (*comment.GetCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComment", varargs...)
	ret0, _ := ret[0].(*comment.GetCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCommentServiceClientMockRecorder) GetComment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCommentServiceClient)(nil).GetComment), varargs...)
}

// ListCommentsByArticleID mocks base method.
func (m *MockCommentServiceClient) ListCommentsByArticleID(ctx context.Context, in *comment.ListCommentsByArticleIDRequest, opts ...grpc.CallOption) (*comment.ListCommentsByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListCommentsByArticleID", varargs...)
	ret0, _ := ret[0].(*comment.ListCommentsByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByArticleID indicates an expected call of ListCommentsByArticleID.
func (mr *MockCommentServiceClientMockRecorder) ListCommentsByArticleID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByArticleID", reflect.TypeOf((*MockCommentServiceClient)(nil).ListCommentsByArticleID), varargs...)
}

// UpdateComment mocks base method.
func (m *MockCommentServiceClient) UpdateComment(ctx context.Context, in *comment.UpdateCommentRequest, opts ...grpc.CallOption) (*comment.UpdateCommentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateComment", varargs...)
	ret0, _ := ret[0].(*comment.UpdateCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentServiceClientMockRecorder) UpdateComment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentServiceClient)(nil).UpdateComment), varargs...)
}

// MockCommentServiceServer is a mock of CommentServiceServer interface.
type MockCommentServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceServerMockRecorder
}

// MockCommentServiceServerMockRecorder is the mock recorder for MockCommentServiceServer.
type MockCommentServiceServerMockRecorder struct {
	mock *MockCommentServiceServer
}

// NewMockCommentServiceServer creates a new mock instance.
func NewMockCommentServiceServer(ctrl *gomock.Controller) *MockCommentServiceServer {
	mock := &MockCommentServiceServer{ctrl: ctrl}
	mock.recorder = &MockCommentServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentServiceServer) EXPECT() *MockCommentServiceServerMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockCommentServiceServer) CreateComment(arg0 context.Context, arg1 *comment.CreateCommentRequest) (*comment.CreateCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1)
	ret0, _ := ret[0].(*comment.CreateCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockCommentServiceServerMockRecorder) CreateComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockCommentServiceServer)(nil).CreateComment), arg0, arg1)
}

// DeleteComment mocks base method.
func (m *MockCommentServiceServer) DeleteComment(arg0 context.Context, arg1 *comment.DeleteCommentRequest) (*comment.DeleteCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1)
	ret0, _ := ret[0].(*comment.DeleteCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentServiceServerMockRecorder) DeleteComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentServiceServer)(nil).DeleteComment), arg0, arg1)
}

// DeleteCommentByArticleID mocks base method.
func (m *MockCommentServiceServer) DeleteCommentByArticleID(arg0 context.Context, arg1 *comment.DeleteCommentByArticleIDRequest) (*comment.DeleteCommentByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentByArticleID", arg0, arg1)
	ret0, _ := ret[0].(*comment.DeleteCommentByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByArticleID indicates an expected call of DeleteCommentByArticleID.
func (mr *MockCommentServiceServerMockRecorder) DeleteCommentByArticleID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByArticleID", reflect.TypeOf((*MockCommentServiceServer)(nil).DeleteCommentByArticleID), arg0, arg1)
}

// DeleteCommentByArticleIDCompensate mocks base method.
func (m *MockCommentServiceServer) DeleteCommentByArticleIDCompensate(arg0 context.Context, arg1 *comment.DeleteCommentByArticleIDRequest) (*comment.DeleteCommentByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentByArticleIDCompensate", arg0, arg1)
	ret0, _ := ret[0].(*comment.DeleteCommentByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByArticleIDCompensate indicates an expected call of DeleteCommentByArticleIDCompensate.
func (mr *MockCommentServiceServerMockRecorder) DeleteCommentByArticleIDCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByArticleIDCompensate", reflect.TypeOf((*MockCommentServiceServer)(nil).DeleteCommentByArticleIDCompensate), arg0, arg1)
}

// DeleteCommentByUserID mocks base method.
func (m *MockCommentServiceServer) DeleteCommentByUserID(arg0 context.Context, arg1 *comment.DeleteCommentByUserIDRequest) (*comment.DeleteCommentByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentByUserID", arg0, arg1)
	ret0, _ := ret[0].(*comment.DeleteCommentByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByUserID indicates an expected call of DeleteCommentByUserID.
func (mr *MockCommentServiceServerMockRecorder) DeleteCommentByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByUserID", reflect.TypeOf((*MockCommentServiceServer)(nil).DeleteCommentByUserID), arg0, arg1)
}

// DeleteCommentByUserIDCompensate mocks base method.
func (m *MockCommentServiceServer) DeleteCommentByUserIDCompensate(arg0 context.Context, arg1 *comment.DeleteCommentByUserIDRequest) (*comment.DeleteCommentByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCommentByUserIDCompensate", arg0, arg1)
	ret0, _ := ret[0].(*comment.DeleteCommentByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCommentByUserIDCompensate indicates an expected call of DeleteCommentByUserIDCompensate.
func (mr *MockCommentServiceServerMockRecorder) DeleteCommentByUserIDCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentByUserIDCompensate", reflect.TypeOf((*MockCommentServiceServer)(nil).DeleteCommentByUserIDCompensate), arg0, arg1)
}

// GetComment mocks base method.
func (m *MockCommentServiceServer) GetComment(arg0 context.Context, arg1 *comment.GetCommentRequest) (*comment.GetCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComment", arg0, arg1)
	ret0, _ := ret[0].(*comment.GetCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComment indicates an expected call of GetComment.
func (mr *MockCommentServiceServerMockRecorder) GetComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComment", reflect.TypeOf((*MockCommentServiceServer)(nil).GetComment), arg0, arg1)
}

// ListCommentsByArticleID mocks base method.
func (m *MockCommentServiceServer) ListCommentsByArticleID(arg0 context.Context, arg1 *comment.ListCommentsByArticleIDRequest) (*comment.ListCommentsByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommentsByArticleID", arg0, arg1)
	ret0, _ := ret[0].(*comment.ListCommentsByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByArticleID indicates an expected call of ListCommentsByArticleID.
func (mr *MockCommentServiceServerMockRecorder) ListCommentsByArticleID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByArticleID", reflect.TypeOf((*MockCommentServiceServer)(nil).ListCommentsByArticleID), arg0, arg1)
}

// UpdateComment mocks base method.
func (m *MockCommentServiceServer) UpdateComment(arg0 context.Context, arg1 *comment.UpdateCommentRequest) (*comment.UpdateCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComment", arg0, arg1)
	ret0, _ := ret[0].(*comment.UpdateCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateComment indicates an expected call of UpdateComment.
func (mr *MockCommentServiceServerMockRecorder) UpdateComment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComment", reflect.TypeOf((*MockCommentServiceServer)(nil).UpdateComment), arg0, arg1)
}

// mustEmbedUnimplementedCommentServiceServer mocks base method.
func (m *MockCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCommentServiceServer")
}

// mustEmbedUnimplementedCommentServiceServer indicates an expected call of mustEmbedUnimplementedCommentServiceServer.
func (mr *MockCommentServiceServerMockRecorder) mustEmbedUnimplementedCommentServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCommentServiceServer", reflect.TypeOf((*MockCommentServiceServer)(nil).mustEmbedUnimplementedCommentServiceServer))
}

// MockUnsafeCommentServiceServer is a mock of UnsafeCommentServiceServer interface.
type MockUnsafeCommentServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCommentServiceServerMockRecorder
}

// MockUnsafeCommentServiceServerMockRecorder is the mock recorder for MockUnsafeCommentServiceServer.
type MockUnsafeCommentServiceServerMockRecorder struct {
	mock *MockUnsafeCommentServiceServer
}

// NewMockUnsafeCommentServiceServer creates a new mock instance.
func NewMockUnsafeCommentServiceServer(ctrl *gomock.Controller) *MockUnsafeCommentServiceServer {
	mock := &MockUnsafeCommentServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCommentServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCommentServiceServer) EXPECT() *MockUnsafeCommentServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCommentServiceServer mocks base method.
func (m *MockUnsafeCommentServiceServer) mustEmbedUnimplementedCommentServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCommentServiceServer")
}

// mustEmbedUnimplementedCommentServiceServer indicates an expected call of mustEmbedUnimplementedCommentServiceServer.
func (mr *MockUnsafeCommentServiceServerMockRecorder) mustEmbedUnimplementedCommentServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCommentServiceServer", reflect.TypeOf((*MockUnsafeCommentServiceServer)(nil).mustEmbedUnimplementedCommentServiceServer))
}
