// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/pkg/config"
	"github.com/loak155/techbranch-backend/pkg/db"
	"github.com/loak155/techbranch-backend/services/user/internal/repository"
	"github.com/loak155/techbranch-backend/services/user/internal/router"
	"github.com/loak155/techbranch-backend/services/user/internal/usecase"
	"github.com/loak155/techbranch-backend/services/user/proto"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (user.UserServiceServer, error) {
	gormDB := db.NewUserDB(conf)
	iUserRepository := repository.NewUserRepository(gormDB)
	iUserUsecase := usecase.NewUserUsecase(iUserRepository)
	userServiceServer := router.NewUserGRPCServer(grpcServer, iUserUsecase)
	return userServiceServer, nil
}
