version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: techbranch
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U root"]
  redis:
    image: redis:6.2-alpine
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog-data:/tmp
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    env_file:
      - .env
    environment:
      DB_SOURCE: postgres://root:secret@postgres:5432/techbranch?sslmode=disable
      REDIS_ADDRESS: redis:6379
      MAIL_ADDRESS: mailhog:1025
    depends_on:
      - postgres
    command: [ "/app/main"]
volumes:
  db-data:
  redis-data:
  mailhog-data: