// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/pkg/config"
	"github.com/loak155/techbranch-backend/pkg/db"
	"github.com/loak155/techbranch-backend/services/article/internal/repository"
	"github.com/loak155/techbranch-backend/services/article/internal/router"
	"github.com/loak155/techbranch-backend/services/article/internal/usecase"
	"github.com/loak155/techbranch-backend/services/article/proto"
	"github.com/loak155/techbranch-backend/services/bookmark/client"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (proto.ArticleServiceServer, error) {
	gormDB := db.NewArticleDB(conf)
	iArticleRepository := repository.NewArticleRepository(gormDB)
	bookmarkServiceClient, err := client.NewBookmarkGRPCClient(conf)
	if err != nil {
		return nil, err
	}
	iArticleUsecase := usecase.NewArticleUsecase(iArticleRepository, bookmarkServiceClient)
	articleServiceServer := router.NewArticleGRPCServer(grpcServer, iArticleUsecase)
	return articleServiceServer, nil
}
