// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/pkg/config"
	"github.com/loak155/techbranch-backend/pkg/db"
	"github.com/loak155/techbranch-backend/pkg/jwt"
	"github.com/loak155/techbranch-backend/services/article/client"
	"github.com/loak155/techbranch-backend/services/bookmark/internal/repository"
	"github.com/loak155/techbranch-backend/services/bookmark/internal/router"
	"github.com/loak155/techbranch-backend/services/bookmark/internal/usecase"
	"github.com/loak155/techbranch-backend/services/bookmark/proto"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (bookmark.BookmarkServiceServer, error) {
	gormDB := db.NewBookmarkDB(conf)
	iBookmarkRepository := repository.NewBookmarkRepository(gormDB)
	articleServiceClient, err := client.NewArticleGRPCClient(conf)
	if err != nil {
		return nil, err
	}
	iBookmarkUsecase := usecase.NewBookmarkUsecase(iBookmarkRepository, articleServiceClient)
	jwtManager := jwt.NewJwtManager(conf)
	bookmarkServiceServer := router.NewBookmarkGRPCServer(grpcServer, iBookmarkUsecase, jwtManager)
	return bookmarkServiceServer, nil
}
