// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto/article_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/loak155/techbranch-backend/services/article/proto"
	grpc "google.golang.org/grpc"
)

// MockArticleServiceClient is a mock of ArticleServiceClient interface.
type MockArticleServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServiceClientMockRecorder
}

// MockArticleServiceClientMockRecorder is the mock recorder for MockArticleServiceClient.
type MockArticleServiceClientMockRecorder struct {
	mock *MockArticleServiceClient
}

// NewMockArticleServiceClient creates a new mock instance.
func NewMockArticleServiceClient(ctrl *gomock.Controller) *MockArticleServiceClient {
	mock := &MockArticleServiceClient{ctrl: ctrl}
	mock.recorder = &MockArticleServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleServiceClient) EXPECT() *MockArticleServiceClientMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockArticleServiceClient) CreateArticle(ctx context.Context, in *proto.CreateArticleRequest, opts ...grpc.CallOption) (*proto.CreateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateArticle", varargs...)
	ret0, _ := ret[0].(*proto.CreateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockArticleServiceClientMockRecorder) CreateArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).CreateArticle), varargs...)
}

// DeleteArticle mocks base method.
func (m *MockArticleServiceClient) DeleteArticle(ctx context.Context, in *proto.DeleteArticleRequest, opts ...grpc.CallOption) (*proto.DeleteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteArticle", varargs...)
	ret0, _ := ret[0].(*proto.DeleteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockArticleServiceClientMockRecorder) DeleteArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).DeleteArticle), varargs...)
}

// GetArticle mocks base method.
func (m *MockArticleServiceClient) GetArticle(ctx context.Context, in *proto.GetArticleRequest, opts ...grpc.CallOption) (*proto.GetArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticle", varargs...)
	ret0, _ := ret[0].(*proto.GetArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleServiceClientMockRecorder) GetArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).GetArticle), varargs...)
}

// GetArticleCount mocks base method.
func (m *MockArticleServiceClient) GetArticleCount(ctx context.Context, in *proto.GetArticleCountRequest, opts ...grpc.CallOption) (*proto.GetArticleCountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetArticleCount", varargs...)
	ret0, _ := ret[0].(*proto.GetArticleCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleCount indicates an expected call of GetArticleCount.
func (mr *MockArticleServiceClientMockRecorder) GetArticleCount(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleCount", reflect.TypeOf((*MockArticleServiceClient)(nil).GetArticleCount), varargs...)
}

// GetBookmarkedArticle mocks base method.
func (m *MockArticleServiceClient) GetBookmarkedArticle(ctx context.Context, in *proto.GetBookmarkedArticleRequest, opts ...grpc.CallOption) (*proto.GetBookmarkedArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBookmarkedArticle", varargs...)
	ret0, _ := ret[0].(*proto.GetBookmarkedArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkedArticle indicates an expected call of GetBookmarkedArticle.
func (mr *MockArticleServiceClientMockRecorder) GetBookmarkedArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkedArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).GetBookmarkedArticle), varargs...)
}

// ListArticles mocks base method.
func (m *MockArticleServiceClient) ListArticles(ctx context.Context, in *proto.ListArticlesRequest, opts ...grpc.CallOption) (*proto.ListArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListArticles", varargs...)
	ret0, _ := ret[0].(*proto.ListArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockArticleServiceClientMockRecorder) ListArticles(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockArticleServiceClient)(nil).ListArticles), varargs...)
}

// UpdateArticle mocks base method.
func (m *MockArticleServiceClient) UpdateArticle(ctx context.Context, in *proto.UpdateArticleRequest, opts ...grpc.CallOption) (*proto.UpdateArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateArticle", varargs...)
	ret0, _ := ret[0].(*proto.UpdateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockArticleServiceClientMockRecorder) UpdateArticle(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockArticleServiceClient)(nil).UpdateArticle), varargs...)
}

// MockArticleServiceServer is a mock of ArticleServiceServer interface.
type MockArticleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArticleServiceServerMockRecorder
}

// MockArticleServiceServerMockRecorder is the mock recorder for MockArticleServiceServer.
type MockArticleServiceServerMockRecorder struct {
	mock *MockArticleServiceServer
}

// NewMockArticleServiceServer creates a new mock instance.
func NewMockArticleServiceServer(ctrl *gomock.Controller) *MockArticleServiceServer {
	mock := &MockArticleServiceServer{ctrl: ctrl}
	mock.recorder = &MockArticleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleServiceServer) EXPECT() *MockArticleServiceServerMockRecorder {
	return m.recorder
}

// CreateArticle mocks base method.
func (m *MockArticleServiceServer) CreateArticle(arg0 context.Context, arg1 *proto.CreateArticleRequest) (*proto.CreateArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArticle", arg0, arg1)
	ret0, _ := ret[0].(*proto.CreateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArticle indicates an expected call of CreateArticle.
func (mr *MockArticleServiceServerMockRecorder) CreateArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).CreateArticle), arg0, arg1)
}

// DeleteArticle mocks base method.
func (m *MockArticleServiceServer) DeleteArticle(arg0 context.Context, arg1 *proto.DeleteArticleRequest) (*proto.DeleteArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArticle", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteArticle indicates an expected call of DeleteArticle.
func (mr *MockArticleServiceServerMockRecorder) DeleteArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).DeleteArticle), arg0, arg1)
}

// GetArticle mocks base method.
func (m *MockArticleServiceServer) GetArticle(arg0 context.Context, arg1 *proto.GetArticleRequest) (*proto.GetArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticle", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticle indicates an expected call of GetArticle.
func (mr *MockArticleServiceServerMockRecorder) GetArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).GetArticle), arg0, arg1)
}

// GetArticleCount mocks base method.
func (m *MockArticleServiceServer) GetArticleCount(arg0 context.Context, arg1 *proto.GetArticleCountRequest) (*proto.GetArticleCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArticleCount", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetArticleCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArticleCount indicates an expected call of GetArticleCount.
func (mr *MockArticleServiceServerMockRecorder) GetArticleCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArticleCount", reflect.TypeOf((*MockArticleServiceServer)(nil).GetArticleCount), arg0, arg1)
}

// GetBookmarkedArticle mocks base method.
func (m *MockArticleServiceServer) GetBookmarkedArticle(arg0 context.Context, arg1 *proto.GetBookmarkedArticleRequest) (*proto.GetBookmarkedArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmarkedArticle", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetBookmarkedArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkedArticle indicates an expected call of GetBookmarkedArticle.
func (mr *MockArticleServiceServerMockRecorder) GetBookmarkedArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkedArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).GetBookmarkedArticle), arg0, arg1)
}

// ListArticles mocks base method.
func (m *MockArticleServiceServer) ListArticles(arg0 context.Context, arg1 *proto.ListArticlesRequest) (*proto.ListArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArticles", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArticles indicates an expected call of ListArticles.
func (mr *MockArticleServiceServerMockRecorder) ListArticles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArticles", reflect.TypeOf((*MockArticleServiceServer)(nil).ListArticles), arg0, arg1)
}

// UpdateArticle mocks base method.
func (m *MockArticleServiceServer) UpdateArticle(arg0 context.Context, arg1 *proto.UpdateArticleRequest) (*proto.UpdateArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateArticle", arg0, arg1)
	ret0, _ := ret[0].(*proto.UpdateArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateArticle indicates an expected call of UpdateArticle.
func (mr *MockArticleServiceServerMockRecorder) UpdateArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateArticle", reflect.TypeOf((*MockArticleServiceServer)(nil).UpdateArticle), arg0, arg1)
}

// mustEmbedUnimplementedArticleServiceServer mocks base method.
func (m *MockArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArticleServiceServer")
}

// mustEmbedUnimplementedArticleServiceServer indicates an expected call of mustEmbedUnimplementedArticleServiceServer.
func (mr *MockArticleServiceServerMockRecorder) mustEmbedUnimplementedArticleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArticleServiceServer", reflect.TypeOf((*MockArticleServiceServer)(nil).mustEmbedUnimplementedArticleServiceServer))
}

// MockUnsafeArticleServiceServer is a mock of UnsafeArticleServiceServer interface.
type MockUnsafeArticleServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeArticleServiceServerMockRecorder
}

// MockUnsafeArticleServiceServerMockRecorder is the mock recorder for MockUnsafeArticleServiceServer.
type MockUnsafeArticleServiceServerMockRecorder struct {
	mock *MockUnsafeArticleServiceServer
}

// NewMockUnsafeArticleServiceServer creates a new mock instance.
func NewMockUnsafeArticleServiceServer(ctrl *gomock.Controller) *MockUnsafeArticleServiceServer {
	mock := &MockUnsafeArticleServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeArticleServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeArticleServiceServer) EXPECT() *MockUnsafeArticleServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedArticleServiceServer mocks base method.
func (m *MockUnsafeArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArticleServiceServer")
}

// mustEmbedUnimplementedArticleServiceServer indicates an expected call of mustEmbedUnimplementedArticleServiceServer.
func (mr *MockUnsafeArticleServiceServerMockRecorder) mustEmbedUnimplementedArticleServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArticleServiceServer", reflect.TypeOf((*MockUnsafeArticleServiceServer)(nil).mustEmbedUnimplementedArticleServiceServer))
}
