// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/bookmark_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/loak155/techbranch-backend/services/bookmark/internal/domain"
)

// MockIBookmarkRepository is a mock of IBookmarkRepository interface.
type MockIBookmarkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBookmarkRepositoryMockRecorder
}

// MockIBookmarkRepositoryMockRecorder is the mock recorder for MockIBookmarkRepository.
type MockIBookmarkRepositoryMockRecorder struct {
	mock *MockIBookmarkRepository
}

// NewMockIBookmarkRepository creates a new mock instance.
func NewMockIBookmarkRepository(ctrl *gomock.Controller) *MockIBookmarkRepository {
	mock := &MockIBookmarkRepository{ctrl: ctrl}
	mock.recorder = &MockIBookmarkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBookmarkRepository) EXPECT() *MockIBookmarkRepositoryMockRecorder {
	return m.recorder
}

// CreateBookmark mocks base method.
func (m *MockIBookmarkRepository) CreateBookmark(bookmark *domain.Bookmark) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookmark", bookmark)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBookmark indicates an expected call of CreateBookmark.
func (mr *MockIBookmarkRepositoryMockRecorder) CreateBookmark(bookmark interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookmark", reflect.TypeOf((*MockIBookmarkRepository)(nil).CreateBookmark), bookmark)
}

// DeleteBookmark mocks base method.
func (m *MockIBookmarkRepository) DeleteBookmark(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmark", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmark indicates an expected call of DeleteBookmark.
func (mr *MockIBookmarkRepositoryMockRecorder) DeleteBookmark(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmark", reflect.TypeOf((*MockIBookmarkRepository)(nil).DeleteBookmark), id)
}

// DeleteBookmarkByArticleID mocks base method.
func (m *MockIBookmarkRepository) DeleteBookmarkByArticleID(ArticleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByArticleID", ArticleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmarkByArticleID indicates an expected call of DeleteBookmarkByArticleID.
func (mr *MockIBookmarkRepositoryMockRecorder) DeleteBookmarkByArticleID(ArticleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByArticleID", reflect.TypeOf((*MockIBookmarkRepository)(nil).DeleteBookmarkByArticleID), ArticleID)
}

// DeleteBookmarkByUserID mocks base method.
func (m *MockIBookmarkRepository) DeleteBookmarkByUserID(UserID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserID", UserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmarkByUserID indicates an expected call of DeleteBookmarkByUserID.
func (mr *MockIBookmarkRepositoryMockRecorder) DeleteBookmarkByUserID(UserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserID", reflect.TypeOf((*MockIBookmarkRepository)(nil).DeleteBookmarkByUserID), UserID)
}

// DeleteBookmarkByUserIDAndArticleID mocks base method.
func (m *MockIBookmarkRepository) DeleteBookmarkByUserIDAndArticleID(userID, articleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserIDAndArticleID", userID, articleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookmarkByUserIDAndArticleID indicates an expected call of DeleteBookmarkByUserIDAndArticleID.
func (mr *MockIBookmarkRepositoryMockRecorder) DeleteBookmarkByUserIDAndArticleID(userID, articleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserIDAndArticleID", reflect.TypeOf((*MockIBookmarkRepository)(nil).DeleteBookmarkByUserIDAndArticleID), userID, articleID)
}

// GetBookmark mocks base method.
func (m *MockIBookmarkRepository) GetBookmark(id int) (*domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmark", id)
	ret0, _ := ret[0].(*domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmark indicates an expected call of GetBookmark.
func (mr *MockIBookmarkRepositoryMockRecorder) GetBookmark(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmark", reflect.TypeOf((*MockIBookmarkRepository)(nil).GetBookmark), id)
}

// GetBookmarkByUserIDAndArticleID mocks base method.
func (m *MockIBookmarkRepository) GetBookmarkByUserIDAndArticleID(userID, articleID int) (*domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmarkByUserIDAndArticleID", userID, articleID)
	ret0, _ := ret[0].(*domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkByUserIDAndArticleID indicates an expected call of GetBookmarkByUserIDAndArticleID.
func (mr *MockIBookmarkRepositoryMockRecorder) GetBookmarkByUserIDAndArticleID(userID, articleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkByUserIDAndArticleID", reflect.TypeOf((*MockIBookmarkRepository)(nil).GetBookmarkByUserIDAndArticleID), userID, articleID)
}

// GetBookmarkByUserIDAndArticleIDWithUnscoped mocks base method.
func (m *MockIBookmarkRepository) GetBookmarkByUserIDAndArticleIDWithUnscoped(userID, articleID int) (*domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmarkByUserIDAndArticleIDWithUnscoped", userID, articleID)
	ret0, _ := ret[0].(*domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkByUserIDAndArticleIDWithUnscoped indicates an expected call of GetBookmarkByUserIDAndArticleIDWithUnscoped.
func (mr *MockIBookmarkRepositoryMockRecorder) GetBookmarkByUserIDAndArticleIDWithUnscoped(userID, articleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkByUserIDAndArticleIDWithUnscoped", reflect.TypeOf((*MockIBookmarkRepository)(nil).GetBookmarkByUserIDAndArticleIDWithUnscoped), userID, articleID)
}

// ListBookmarks mocks base method.
func (m *MockIBookmarkRepository) ListBookmarks() (*[]domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarks")
	ret0, _ := ret[0].(*[]domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarks indicates an expected call of ListBookmarks.
func (mr *MockIBookmarkRepositoryMockRecorder) ListBookmarks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarks", reflect.TypeOf((*MockIBookmarkRepository)(nil).ListBookmarks))
}

// ListBookmarksByArticleID mocks base method.
func (m *MockIBookmarkRepository) ListBookmarksByArticleID(articleID int) (*[]domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarksByArticleID", articleID)
	ret0, _ := ret[0].(*[]domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByArticleID indicates an expected call of ListBookmarksByArticleID.
func (mr *MockIBookmarkRepositoryMockRecorder) ListBookmarksByArticleID(articleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByArticleID", reflect.TypeOf((*MockIBookmarkRepository)(nil).ListBookmarksByArticleID), articleID)
}

// ListBookmarksByUserID mocks base method.
func (m *MockIBookmarkRepository) ListBookmarksByUserID(userID int) (*[]domain.Bookmark, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarksByUserID", userID)
	ret0, _ := ret[0].(*[]domain.Bookmark)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByUserID indicates an expected call of ListBookmarksByUserID.
func (mr *MockIBookmarkRepositoryMockRecorder) ListBookmarksByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByUserID", reflect.TypeOf((*MockIBookmarkRepository)(nil).ListBookmarksByUserID), userID)
}

// UpdateBookmarkByArticleIDWithUnscoped mocks base method.
func (m *MockIBookmarkRepository) UpdateBookmarkByArticleIDWithUnscoped(ArticleID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookmarkByArticleIDWithUnscoped", ArticleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookmarkByArticleIDWithUnscoped indicates an expected call of UpdateBookmarkByArticleIDWithUnscoped.
func (mr *MockIBookmarkRepositoryMockRecorder) UpdateBookmarkByArticleIDWithUnscoped(ArticleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookmarkByArticleIDWithUnscoped", reflect.TypeOf((*MockIBookmarkRepository)(nil).UpdateBookmarkByArticleIDWithUnscoped), ArticleID)
}

// UpdateBookmarkByUserIDWithUnscoped mocks base method.
func (m *MockIBookmarkRepository) UpdateBookmarkByUserIDWithUnscoped(UserID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookmarkByUserIDWithUnscoped", UserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookmarkByUserIDWithUnscoped indicates an expected call of UpdateBookmarkByUserIDWithUnscoped.
func (mr *MockIBookmarkRepositoryMockRecorder) UpdateBookmarkByUserIDWithUnscoped(UserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookmarkByUserIDWithUnscoped", reflect.TypeOf((*MockIBookmarkRepository)(nil).UpdateBookmarkByUserIDWithUnscoped), UserID)
}

// UpdateBookmarkWithUnscoped mocks base method.
func (m *MockIBookmarkRepository) UpdateBookmarkWithUnscoped(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookmarkWithUnscoped", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBookmarkWithUnscoped indicates an expected call of UpdateBookmarkWithUnscoped.
func (mr *MockIBookmarkRepositoryMockRecorder) UpdateBookmarkWithUnscoped(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookmarkWithUnscoped", reflect.TypeOf((*MockIBookmarkRepository)(nil).UpdateBookmarkWithUnscoped), id)
}
