// Code generated by MockGen. DO NOT EDIT.
// Source: ./proto/bookmark_grpc.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/loak155/techbranch-backend/services/bookmark/proto"
	grpc "google.golang.org/grpc"
)

// MockBookmarkServiceClient is a mock of BookmarkServiceClient interface.
type MockBookmarkServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBookmarkServiceClientMockRecorder
}

// MockBookmarkServiceClientMockRecorder is the mock recorder for MockBookmarkServiceClient.
type MockBookmarkServiceClientMockRecorder struct {
	mock *MockBookmarkServiceClient
}

// NewMockBookmarkServiceClient creates a new mock instance.
func NewMockBookmarkServiceClient(ctrl *gomock.Controller) *MockBookmarkServiceClient {
	mock := &MockBookmarkServiceClient{ctrl: ctrl}
	mock.recorder = &MockBookmarkServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookmarkServiceClient) EXPECT() *MockBookmarkServiceClientMockRecorder {
	return m.recorder
}

// CreateBookmark mocks base method.
func (m *MockBookmarkServiceClient) CreateBookmark(ctx context.Context, in *proto.CreateBookmarkRequest, opts ...grpc.CallOption) (*proto.CreateBookmarkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBookmark", varargs...)
	ret0, _ := ret[0].(*proto.CreateBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookmark indicates an expected call of CreateBookmark.
func (mr *MockBookmarkServiceClientMockRecorder) CreateBookmark(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookmark", reflect.TypeOf((*MockBookmarkServiceClient)(nil).CreateBookmark), varargs...)
}

// DeleteBookmark mocks base method.
func (m *MockBookmarkServiceClient) DeleteBookmark(ctx context.Context, in *proto.DeleteBookmarkRequest, opts ...grpc.CallOption) (*proto.DeleteBookmarkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBookmark", varargs...)
	ret0, _ := ret[0].(*proto.DeleteBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmark indicates an expected call of DeleteBookmark.
func (mr *MockBookmarkServiceClientMockRecorder) DeleteBookmark(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmark", reflect.TypeOf((*MockBookmarkServiceClient)(nil).DeleteBookmark), varargs...)
}

// DeleteBookmarkByArticleID mocks base method.
func (m *MockBookmarkServiceClient) DeleteBookmarkByArticleID(ctx context.Context, in *proto.DeleteBookmarkByArticleIDRequest, opts ...grpc.CallOption) (*proto.DeleteBookmarkByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBookmarkByArticleID", varargs...)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByArticleID indicates an expected call of DeleteBookmarkByArticleID.
func (mr *MockBookmarkServiceClientMockRecorder) DeleteBookmarkByArticleID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByArticleID", reflect.TypeOf((*MockBookmarkServiceClient)(nil).DeleteBookmarkByArticleID), varargs...)
}

// DeleteBookmarkByArticleIDCompensate mocks base method.
func (m *MockBookmarkServiceClient) DeleteBookmarkByArticleIDCompensate(ctx context.Context, in *proto.DeleteBookmarkByArticleIDRequest, opts ...grpc.CallOption) (*proto.DeleteBookmarkByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBookmarkByArticleIDCompensate", varargs...)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByArticleIDCompensate indicates an expected call of DeleteBookmarkByArticleIDCompensate.
func (mr *MockBookmarkServiceClientMockRecorder) DeleteBookmarkByArticleIDCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByArticleIDCompensate", reflect.TypeOf((*MockBookmarkServiceClient)(nil).DeleteBookmarkByArticleIDCompensate), varargs...)
}

// DeleteBookmarkByUserID mocks base method.
func (m *MockBookmarkServiceClient) DeleteBookmarkByUserID(ctx context.Context, in *proto.DeleteBookmarkByUserIDRequest, opts ...grpc.CallOption) (*proto.DeleteBookmarkByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserID", varargs...)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByUserID indicates an expected call of DeleteBookmarkByUserID.
func (mr *MockBookmarkServiceClientMockRecorder) DeleteBookmarkByUserID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserID", reflect.TypeOf((*MockBookmarkServiceClient)(nil).DeleteBookmarkByUserID), varargs...)
}

// DeleteBookmarkByUserIDCompensate mocks base method.
func (m *MockBookmarkServiceClient) DeleteBookmarkByUserIDCompensate(ctx context.Context, in *proto.DeleteBookmarkByUserIDRequest, opts ...grpc.CallOption) (*proto.DeleteBookmarkByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserIDCompensate", varargs...)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByUserIDCompensate indicates an expected call of DeleteBookmarkByUserIDCompensate.
func (mr *MockBookmarkServiceClientMockRecorder) DeleteBookmarkByUserIDCompensate(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserIDCompensate", reflect.TypeOf((*MockBookmarkServiceClient)(nil).DeleteBookmarkByUserIDCompensate), varargs...)
}

// GetBookmark mocks base method.
func (m *MockBookmarkServiceClient) GetBookmark(ctx context.Context, in *proto.GetBookmarkRequest, opts ...grpc.CallOption) (*proto.GetBookmarkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBookmark", varargs...)
	ret0, _ := ret[0].(*proto.GetBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmark indicates an expected call of GetBookmark.
func (mr *MockBookmarkServiceClientMockRecorder) GetBookmark(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmark", reflect.TypeOf((*MockBookmarkServiceClient)(nil).GetBookmark), varargs...)
}

// GetBookmarkCountByArticleID mocks base method.
func (m *MockBookmarkServiceClient) GetBookmarkCountByArticleID(ctx context.Context, in *proto.GetBookmarkCountByArticleIDRequest, opts ...grpc.CallOption) (*proto.GetBookmarkCountByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBookmarkCountByArticleID", varargs...)
	ret0, _ := ret[0].(*proto.GetBookmarkCountByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkCountByArticleID indicates an expected call of GetBookmarkCountByArticleID.
func (mr *MockBookmarkServiceClientMockRecorder) GetBookmarkCountByArticleID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkCountByArticleID", reflect.TypeOf((*MockBookmarkServiceClient)(nil).GetBookmarkCountByArticleID), varargs...)
}

// ListBookmarks mocks base method.
func (m *MockBookmarkServiceClient) ListBookmarks(ctx context.Context, in *proto.ListBookmarksRequest, opts ...grpc.CallOption) (*proto.ListBookmarksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBookmarks", varargs...)
	ret0, _ := ret[0].(*proto.ListBookmarksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarks indicates an expected call of ListBookmarks.
func (mr *MockBookmarkServiceClientMockRecorder) ListBookmarks(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarks", reflect.TypeOf((*MockBookmarkServiceClient)(nil).ListBookmarks), varargs...)
}

// ListBookmarksByArticleID mocks base method.
func (m *MockBookmarkServiceClient) ListBookmarksByArticleID(ctx context.Context, in *proto.ListBookmarksByArticleIDRequest, opts ...grpc.CallOption) (*proto.ListBookmarksByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBookmarksByArticleID", varargs...)
	ret0, _ := ret[0].(*proto.ListBookmarksByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByArticleID indicates an expected call of ListBookmarksByArticleID.
func (mr *MockBookmarkServiceClientMockRecorder) ListBookmarksByArticleID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByArticleID", reflect.TypeOf((*MockBookmarkServiceClient)(nil).ListBookmarksByArticleID), varargs...)
}

// ListBookmarksByUserID mocks base method.
func (m *MockBookmarkServiceClient) ListBookmarksByUserID(ctx context.Context, in *proto.ListBookmarksByUserIDRequest, opts ...grpc.CallOption) (*proto.ListBookmarksByUserIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListBookmarksByUserID", varargs...)
	ret0, _ := ret[0].(*proto.ListBookmarksByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByUserID indicates an expected call of ListBookmarksByUserID.
func (mr *MockBookmarkServiceClientMockRecorder) ListBookmarksByUserID(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByUserID", reflect.TypeOf((*MockBookmarkServiceClient)(nil).ListBookmarksByUserID), varargs...)
}

// MockBookmarkServiceServer is a mock of BookmarkServiceServer interface.
type MockBookmarkServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockBookmarkServiceServerMockRecorder
}

// MockBookmarkServiceServerMockRecorder is the mock recorder for MockBookmarkServiceServer.
type MockBookmarkServiceServerMockRecorder struct {
	mock *MockBookmarkServiceServer
}

// NewMockBookmarkServiceServer creates a new mock instance.
func NewMockBookmarkServiceServer(ctrl *gomock.Controller) *MockBookmarkServiceServer {
	mock := &MockBookmarkServiceServer{ctrl: ctrl}
	mock.recorder = &MockBookmarkServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookmarkServiceServer) EXPECT() *MockBookmarkServiceServerMockRecorder {
	return m.recorder
}

// CreateBookmark mocks base method.
func (m *MockBookmarkServiceServer) CreateBookmark(arg0 context.Context, arg1 *proto.CreateBookmarkRequest) (*proto.CreateBookmarkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookmark", arg0, arg1)
	ret0, _ := ret[0].(*proto.CreateBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookmark indicates an expected call of CreateBookmark.
func (mr *MockBookmarkServiceServerMockRecorder) CreateBookmark(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookmark", reflect.TypeOf((*MockBookmarkServiceServer)(nil).CreateBookmark), arg0, arg1)
}

// DeleteBookmark mocks base method.
func (m *MockBookmarkServiceServer) DeleteBookmark(arg0 context.Context, arg1 *proto.DeleteBookmarkRequest) (*proto.DeleteBookmarkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmark", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmark indicates an expected call of DeleteBookmark.
func (mr *MockBookmarkServiceServerMockRecorder) DeleteBookmark(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmark", reflect.TypeOf((*MockBookmarkServiceServer)(nil).DeleteBookmark), arg0, arg1)
}

// DeleteBookmarkByArticleID mocks base method.
func (m *MockBookmarkServiceServer) DeleteBookmarkByArticleID(arg0 context.Context, arg1 *proto.DeleteBookmarkByArticleIDRequest) (*proto.DeleteBookmarkByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByArticleID", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByArticleID indicates an expected call of DeleteBookmarkByArticleID.
func (mr *MockBookmarkServiceServerMockRecorder) DeleteBookmarkByArticleID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByArticleID", reflect.TypeOf((*MockBookmarkServiceServer)(nil).DeleteBookmarkByArticleID), arg0, arg1)
}

// DeleteBookmarkByArticleIDCompensate mocks base method.
func (m *MockBookmarkServiceServer) DeleteBookmarkByArticleIDCompensate(arg0 context.Context, arg1 *proto.DeleteBookmarkByArticleIDRequest) (*proto.DeleteBookmarkByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByArticleIDCompensate", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByArticleIDCompensate indicates an expected call of DeleteBookmarkByArticleIDCompensate.
func (mr *MockBookmarkServiceServerMockRecorder) DeleteBookmarkByArticleIDCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByArticleIDCompensate", reflect.TypeOf((*MockBookmarkServiceServer)(nil).DeleteBookmarkByArticleIDCompensate), arg0, arg1)
}

// DeleteBookmarkByUserID mocks base method.
func (m *MockBookmarkServiceServer) DeleteBookmarkByUserID(arg0 context.Context, arg1 *proto.DeleteBookmarkByUserIDRequest) (*proto.DeleteBookmarkByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserID", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByUserID indicates an expected call of DeleteBookmarkByUserID.
func (mr *MockBookmarkServiceServerMockRecorder) DeleteBookmarkByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserID", reflect.TypeOf((*MockBookmarkServiceServer)(nil).DeleteBookmarkByUserID), arg0, arg1)
}

// DeleteBookmarkByUserIDCompensate mocks base method.
func (m *MockBookmarkServiceServer) DeleteBookmarkByUserIDCompensate(arg0 context.Context, arg1 *proto.DeleteBookmarkByUserIDRequest) (*proto.DeleteBookmarkByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookmarkByUserIDCompensate", arg0, arg1)
	ret0, _ := ret[0].(*proto.DeleteBookmarkByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBookmarkByUserIDCompensate indicates an expected call of DeleteBookmarkByUserIDCompensate.
func (mr *MockBookmarkServiceServerMockRecorder) DeleteBookmarkByUserIDCompensate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookmarkByUserIDCompensate", reflect.TypeOf((*MockBookmarkServiceServer)(nil).DeleteBookmarkByUserIDCompensate), arg0, arg1)
}

// GetBookmark mocks base method.
func (m *MockBookmarkServiceServer) GetBookmark(arg0 context.Context, arg1 *proto.GetBookmarkRequest) (*proto.GetBookmarkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmark", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetBookmarkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmark indicates an expected call of GetBookmark.
func (mr *MockBookmarkServiceServerMockRecorder) GetBookmark(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmark", reflect.TypeOf((*MockBookmarkServiceServer)(nil).GetBookmark), arg0, arg1)
}

// GetBookmarkCountByArticleID mocks base method.
func (m *MockBookmarkServiceServer) GetBookmarkCountByArticleID(arg0 context.Context, arg1 *proto.GetBookmarkCountByArticleIDRequest) (*proto.GetBookmarkCountByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookmarkCountByArticleID", arg0, arg1)
	ret0, _ := ret[0].(*proto.GetBookmarkCountByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookmarkCountByArticleID indicates an expected call of GetBookmarkCountByArticleID.
func (mr *MockBookmarkServiceServerMockRecorder) GetBookmarkCountByArticleID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookmarkCountByArticleID", reflect.TypeOf((*MockBookmarkServiceServer)(nil).GetBookmarkCountByArticleID), arg0, arg1)
}

// ListBookmarks mocks base method.
func (m *MockBookmarkServiceServer) ListBookmarks(arg0 context.Context, arg1 *proto.ListBookmarksRequest) (*proto.ListBookmarksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarks", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListBookmarksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarks indicates an expected call of ListBookmarks.
func (mr *MockBookmarkServiceServerMockRecorder) ListBookmarks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarks", reflect.TypeOf((*MockBookmarkServiceServer)(nil).ListBookmarks), arg0, arg1)
}

// ListBookmarksByArticleID mocks base method.
func (m *MockBookmarkServiceServer) ListBookmarksByArticleID(arg0 context.Context, arg1 *proto.ListBookmarksByArticleIDRequest) (*proto.ListBookmarksByArticleIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarksByArticleID", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListBookmarksByArticleIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByArticleID indicates an expected call of ListBookmarksByArticleID.
func (mr *MockBookmarkServiceServerMockRecorder) ListBookmarksByArticleID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByArticleID", reflect.TypeOf((*MockBookmarkServiceServer)(nil).ListBookmarksByArticleID), arg0, arg1)
}

// ListBookmarksByUserID mocks base method.
func (m *MockBookmarkServiceServer) ListBookmarksByUserID(arg0 context.Context, arg1 *proto.ListBookmarksByUserIDRequest) (*proto.ListBookmarksByUserIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookmarksByUserID", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListBookmarksByUserIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBookmarksByUserID indicates an expected call of ListBookmarksByUserID.
func (mr *MockBookmarkServiceServerMockRecorder) ListBookmarksByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookmarksByUserID", reflect.TypeOf((*MockBookmarkServiceServer)(nil).ListBookmarksByUserID), arg0, arg1)
}

// mustEmbedUnimplementedBookmarkServiceServer mocks base method.
func (m *MockBookmarkServiceServer) mustEmbedUnimplementedBookmarkServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBookmarkServiceServer")
}

// mustEmbedUnimplementedBookmarkServiceServer indicates an expected call of mustEmbedUnimplementedBookmarkServiceServer.
func (mr *MockBookmarkServiceServerMockRecorder) mustEmbedUnimplementedBookmarkServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBookmarkServiceServer", reflect.TypeOf((*MockBookmarkServiceServer)(nil).mustEmbedUnimplementedBookmarkServiceServer))
}

// MockUnsafeBookmarkServiceServer is a mock of UnsafeBookmarkServiceServer interface.
type MockUnsafeBookmarkServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeBookmarkServiceServerMockRecorder
}

// MockUnsafeBookmarkServiceServerMockRecorder is the mock recorder for MockUnsafeBookmarkServiceServer.
type MockUnsafeBookmarkServiceServerMockRecorder struct {
	mock *MockUnsafeBookmarkServiceServer
}

// NewMockUnsafeBookmarkServiceServer creates a new mock instance.
func NewMockUnsafeBookmarkServiceServer(ctrl *gomock.Controller) *MockUnsafeBookmarkServiceServer {
	mock := &MockUnsafeBookmarkServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeBookmarkServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeBookmarkServiceServer) EXPECT() *MockUnsafeBookmarkServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedBookmarkServiceServer mocks base method.
func (m *MockUnsafeBookmarkServiceServer) mustEmbedUnimplementedBookmarkServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBookmarkServiceServer")
}

// mustEmbedUnimplementedBookmarkServiceServer indicates an expected call of mustEmbedUnimplementedBookmarkServiceServer.
func (mr *MockUnsafeBookmarkServiceServerMockRecorder) mustEmbedUnimplementedBookmarkServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBookmarkServiceServer", reflect.TypeOf((*MockUnsafeBookmarkServiceServer)(nil).mustEmbedUnimplementedBookmarkServiceServer))
}
