// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/pkg/config"
	"github.com/loak155/techbranch-backend/pkg/jwt"
	"github.com/loak155/techbranch-backend/pkg/oauth"
	"github.com/loak155/techbranch-backend/services/auth/internal/router"
	"github.com/loak155/techbranch-backend/services/auth/internal/usecase"
	"github.com/loak155/techbranch-backend/services/auth/proto"
	"github.com/loak155/techbranch-backend/services/user/client"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (auth.AuthServiceServer, error) {
	userServiceClient, err := client.NewUserGRPCClient(conf)
	if err != nil {
		return nil, err
	}
	jwtManager := jwt.NewJwtManager(conf)
	google := oauth.NewGoogle(conf)
	iAuthUsecase := usecase.NewAuthUsecase(userServiceClient, jwtManager, google)
	authServiceServer := router.NewAuthGRPCServer(grpcServer, iAuthUsecase, jwtManager)
	return authServiceServer, nil
}
