// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: bookmark.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BookmarkService_CreateBookmark_FullMethodName                     = "/proto.BookmarkService/CreateBookmark"
	BookmarkService_GetBookmarkCountByArticleID_FullMethodName        = "/proto.BookmarkService/GetBookmarkCountByArticleID"
	BookmarkService_ListBookmarksByUserID_FullMethodName              = "/proto.BookmarkService/ListBookmarksByUserID"
	BookmarkService_ListBookmarksByArticleID_FullMethodName           = "/proto.BookmarkService/ListBookmarksByArticleID"
	BookmarkService_DeleteBookmarkByUserIDAndArticleID_FullMethodName = "/proto.BookmarkService/DeleteBookmarkByUserIDAndArticleID"
	BookmarkService_DeleteBookmarkByUserID_FullMethodName             = "/proto.BookmarkService/DeleteBookmarkByUserID"
	BookmarkService_DeleteBookmarkByArticleID_FullMethodName          = "/proto.BookmarkService/DeleteBookmarkByArticleID"
)

// BookmarkServiceClient is the client API for BookmarkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookmarkServiceClient interface {
	CreateBookmark(ctx context.Context, in *CreateBookmarkRequest, opts ...grpc.CallOption) (*CreateBookmarkResponse, error)
	GetBookmarkCountByArticleID(ctx context.Context, in *GetBookmarkCountByArticleIDRequest, opts ...grpc.CallOption) (*GetBookmarkCountByArticleIDResponse, error)
	ListBookmarksByUserID(ctx context.Context, in *ListBookmarksByUserIDRequest, opts ...grpc.CallOption) (*ListBookmarksByUserIDResponse, error)
	ListBookmarksByArticleID(ctx context.Context, in *ListBookmarksByArticleIDRequest, opts ...grpc.CallOption) (*ListBookmarksByArticleIDResponse, error)
	DeleteBookmarkByUserIDAndArticleID(ctx context.Context, in *DeleteBookmarkByUserIDAndArticleIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByUserIDAndArticleIDResponse, error)
	DeleteBookmarkByUserID(ctx context.Context, in *DeleteBookmarkByUserIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByUserIDResponse, error)
	DeleteBookmarkByArticleID(ctx context.Context, in *DeleteBookmarkByArticleIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByArticleIDResponse, error)
}

type bookmarkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookmarkServiceClient(cc grpc.ClientConnInterface) BookmarkServiceClient {
	return &bookmarkServiceClient{cc}
}

func (c *bookmarkServiceClient) CreateBookmark(ctx context.Context, in *CreateBookmarkRequest, opts ...grpc.CallOption) (*CreateBookmarkResponse, error) {
	out := new(CreateBookmarkResponse)
	err := c.cc.Invoke(ctx, BookmarkService_CreateBookmark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) GetBookmarkCountByArticleID(ctx context.Context, in *GetBookmarkCountByArticleIDRequest, opts ...grpc.CallOption) (*GetBookmarkCountByArticleIDResponse, error) {
	out := new(GetBookmarkCountByArticleIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_GetBookmarkCountByArticleID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) ListBookmarksByUserID(ctx context.Context, in *ListBookmarksByUserIDRequest, opts ...grpc.CallOption) (*ListBookmarksByUserIDResponse, error) {
	out := new(ListBookmarksByUserIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_ListBookmarksByUserID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) ListBookmarksByArticleID(ctx context.Context, in *ListBookmarksByArticleIDRequest, opts ...grpc.CallOption) (*ListBookmarksByArticleIDResponse, error) {
	out := new(ListBookmarksByArticleIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_ListBookmarksByArticleID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) DeleteBookmarkByUserIDAndArticleID(ctx context.Context, in *DeleteBookmarkByUserIDAndArticleIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByUserIDAndArticleIDResponse, error) {
	out := new(DeleteBookmarkByUserIDAndArticleIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_DeleteBookmarkByUserIDAndArticleID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) DeleteBookmarkByUserID(ctx context.Context, in *DeleteBookmarkByUserIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByUserIDResponse, error) {
	out := new(DeleteBookmarkByUserIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_DeleteBookmarkByUserID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookmarkServiceClient) DeleteBookmarkByArticleID(ctx context.Context, in *DeleteBookmarkByArticleIDRequest, opts ...grpc.CallOption) (*DeleteBookmarkByArticleIDResponse, error) {
	out := new(DeleteBookmarkByArticleIDResponse)
	err := c.cc.Invoke(ctx, BookmarkService_DeleteBookmarkByArticleID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookmarkServiceServer is the server API for BookmarkService service.
// All implementations must embed UnimplementedBookmarkServiceServer
// for forward compatibility
type BookmarkServiceServer interface {
	CreateBookmark(context.Context, *CreateBookmarkRequest) (*CreateBookmarkResponse, error)
	GetBookmarkCountByArticleID(context.Context, *GetBookmarkCountByArticleIDRequest) (*GetBookmarkCountByArticleIDResponse, error)
	ListBookmarksByUserID(context.Context, *ListBookmarksByUserIDRequest) (*ListBookmarksByUserIDResponse, error)
	ListBookmarksByArticleID(context.Context, *ListBookmarksByArticleIDRequest) (*ListBookmarksByArticleIDResponse, error)
	DeleteBookmarkByUserIDAndArticleID(context.Context, *DeleteBookmarkByUserIDAndArticleIDRequest) (*DeleteBookmarkByUserIDAndArticleIDResponse, error)
	DeleteBookmarkByUserID(context.Context, *DeleteBookmarkByUserIDRequest) (*DeleteBookmarkByUserIDResponse, error)
	DeleteBookmarkByArticleID(context.Context, *DeleteBookmarkByArticleIDRequest) (*DeleteBookmarkByArticleIDResponse, error)
	mustEmbedUnimplementedBookmarkServiceServer()
}

// UnimplementedBookmarkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookmarkServiceServer struct {
}

func (UnimplementedBookmarkServiceServer) CreateBookmark(context.Context, *CreateBookmarkRequest) (*CreateBookmarkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBookmark not implemented")
}
func (UnimplementedBookmarkServiceServer) GetBookmarkCountByArticleID(context.Context, *GetBookmarkCountByArticleIDRequest) (*GetBookmarkCountByArticleIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookmarkCountByArticleID not implemented")
}
func (UnimplementedBookmarkServiceServer) ListBookmarksByUserID(context.Context, *ListBookmarksByUserIDRequest) (*ListBookmarksByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBookmarksByUserID not implemented")
}
func (UnimplementedBookmarkServiceServer) ListBookmarksByArticleID(context.Context, *ListBookmarksByArticleIDRequest) (*ListBookmarksByArticleIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBookmarksByArticleID not implemented")
}
func (UnimplementedBookmarkServiceServer) DeleteBookmarkByUserIDAndArticleID(context.Context, *DeleteBookmarkByUserIDAndArticleIDRequest) (*DeleteBookmarkByUserIDAndArticleIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookmarkByUserIDAndArticleID not implemented")
}
func (UnimplementedBookmarkServiceServer) DeleteBookmarkByUserID(context.Context, *DeleteBookmarkByUserIDRequest) (*DeleteBookmarkByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookmarkByUserID not implemented")
}
func (UnimplementedBookmarkServiceServer) DeleteBookmarkByArticleID(context.Context, *DeleteBookmarkByArticleIDRequest) (*DeleteBookmarkByArticleIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookmarkByArticleID not implemented")
}
func (UnimplementedBookmarkServiceServer) mustEmbedUnimplementedBookmarkServiceServer() {}

// UnsafeBookmarkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookmarkServiceServer will
// result in compilation errors.
type UnsafeBookmarkServiceServer interface {
	mustEmbedUnimplementedBookmarkServiceServer()
}

func RegisterBookmarkServiceServer(s grpc.ServiceRegistrar, srv BookmarkServiceServer) {
	s.RegisterService(&BookmarkService_ServiceDesc, srv)
}

func _BookmarkService_CreateBookmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).CreateBookmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_CreateBookmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).CreateBookmark(ctx, req.(*CreateBookmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_GetBookmarkCountByArticleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookmarkCountByArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).GetBookmarkCountByArticleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_GetBookmarkCountByArticleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).GetBookmarkCountByArticleID(ctx, req.(*GetBookmarkCountByArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_ListBookmarksByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookmarksByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).ListBookmarksByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_ListBookmarksByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).ListBookmarksByUserID(ctx, req.(*ListBookmarksByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_ListBookmarksByArticleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookmarksByArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).ListBookmarksByArticleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_ListBookmarksByArticleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).ListBookmarksByArticleID(ctx, req.(*ListBookmarksByArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_DeleteBookmarkByUserIDAndArticleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookmarkByUserIDAndArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).DeleteBookmarkByUserIDAndArticleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_DeleteBookmarkByUserIDAndArticleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).DeleteBookmarkByUserIDAndArticleID(ctx, req.(*DeleteBookmarkByUserIDAndArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_DeleteBookmarkByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookmarkByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).DeleteBookmarkByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_DeleteBookmarkByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).DeleteBookmarkByUserID(ctx, req.(*DeleteBookmarkByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookmarkService_DeleteBookmarkByArticleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookmarkByArticleIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookmarkServiceServer).DeleteBookmarkByArticleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookmarkService_DeleteBookmarkByArticleID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookmarkServiceServer).DeleteBookmarkByArticleID(ctx, req.(*DeleteBookmarkByArticleIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookmarkService_ServiceDesc is the grpc.ServiceDesc for BookmarkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookmarkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BookmarkService",
	HandlerType: (*BookmarkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBookmark",
			Handler:    _BookmarkService_CreateBookmark_Handler,
		},
		{
			MethodName: "GetBookmarkCountByArticleID",
			Handler:    _BookmarkService_GetBookmarkCountByArticleID_Handler,
		},
		{
			MethodName: "ListBookmarksByUserID",
			Handler:    _BookmarkService_ListBookmarksByUserID_Handler,
		},
		{
			MethodName: "ListBookmarksByArticleID",
			Handler:    _BookmarkService_ListBookmarksByArticleID_Handler,
		},
		{
			MethodName: "DeleteBookmarkByUserIDAndArticleID",
			Handler:    _BookmarkService_DeleteBookmarkByUserIDAndArticleID_Handler,
		},
		{
			MethodName: "DeleteBookmarkByUserID",
			Handler:    _BookmarkService_DeleteBookmarkByUserID_Handler,
		},
		{
			MethodName: "DeleteBookmarkByArticleID",
			Handler:    _BookmarkService_DeleteBookmarkByArticleID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookmark.proto",
}
