// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/loak155/techbranch-backend/pkg/config"
	"github.com/loak155/techbranch-backend/pkg/db"
	"github.com/loak155/techbranch-backend/pkg/jwt"
	"github.com/loak155/techbranch-backend/services/comment/internal/repository"
	"github.com/loak155/techbranch-backend/services/comment/internal/router"
	"github.com/loak155/techbranch-backend/services/comment/internal/usecase"
	"github.com/loak155/techbranch-backend/services/comment/proto"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitServer(conf *config.Config, grpcServer *grpc.Server) (proto.CommentServiceServer, error) {
	gormDB := db.NewCommentDB(conf)
	iCommentRepository := repository.NewCommentRepository(gormDB)
	iCommentUsecase := usecase.NewCommentUsecase(iCommentRepository)
	jwtManager := jwt.NewJwtManager(conf)
	commentServiceServer := router.NewCommentGRPCServer(grpcServer, iCommentUsecase, jwtManager)
	return commentServiceServer, nil
}
